name: travel_tracker
description: A travel tracking app to mark visited countries and cities
publish_to: none

version: 1.0.0+1

environment:
  sdk: '>=3.8.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # UI
  cupertino_icons: ^1.0.8
  
  # Local Storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.4
  
  # Map
  flutter_map: ^7.0.2
  latlong2: ^0.9.1
  
  # Network & Backend
  http: ^1.2.1
  supabase_flutter: ^2.8.0
  
  # File Handling
  file_picker: ^8.0.0
  
  # Utilities
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.13
  uuid: ^4.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/geo/world_countries_simplified.geojson